contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #nftest channel"
    url: https://nfcore.slack.com/channels/nftest
    about: Discussion about the nf-core/nftest pipeline
